### ISSUE TITLE
Bunded with Godot?

### ISSUE THREAD

**Issue by bhgsbatista** [arkology/ShaderV#1]
This seems like a key component of an artist's workflow. Shouldn't this tool be bundled with Godot by default?

**Comment by asheraryam** [comment]
Godot has a visual shader for years now (and continuously updated for better workflow and nodes), this plugin just adds more custom nodes afaik.

https://godot.readthedocs.io/en/latest/tutorials/plugins/editor/visual_shader_plugins.html

https://godotengine.org/article/major-update-for-visual-shader-in-godot-3-2

**Comment by arkology** [comment]
I'm 100% sure that it shouldn't be build into Godot by default. It is too specific.
