### ISSUE TITLE
Godot 4.0 support

### ISSUE THREAD

**Issue by thomasgauthier** [arkology/ShaderV#14]
Is this in the plans for ShaderV?

Could help out if PR are welcome.

**Comment by arkology** [comment]
@thomasgauthier PR is VERY welcome!
I had plans to support 4.x (this is what https://github.com/arkology/ShaderV/pull/12 was made for - to use #include keyword somehow in 4.x), but now, as always, I have no free time for anything other than my PhD dissertation :(

**Comment by thomasgauthier** [comment]
@arkology I got everything working again in 4.0. See #15

**Comment by arkology** [comment]
Fixed by #15 
Thanks for your contribution!
