### ISSUE TITLE
Exporting generated shaders to shadertoy.com

### ISSUE THREAD

**Issue by boulabiar** [arkology/ShaderV#2]
Is it possible to export the shader to be used on shadertoy or within webgl with three.js?

**Comment by arkology** [comment]
@boulabiar hmm, yes, maybe? I don't really know, because i've never used three.js. 
As for Shadertoy, look this: https://docs.godotengine.org/en/latest/tutorials/shading/migrating_to_godot_shader_language.html#shadertoy
