### ISSUE TITLE
Colors in Spherical UV look bleak

### ISSUE THREAD

**Issue by rakun99** [arkology/ShaderV#21]
Spherical UV is a cool effect, but sadly, colors of Texture in the Spherical UV look pretty much bleaker and duller, than just  texture in sprite.

**Comment by arkology** [comment]
This node is supposed to manipulate UV like any other UV manipulating node and should not change texture colors (I'm not shader guru, but I don't think there are any situations where UV manipulation affects texture colors). Try to use any other UV manipulating node and compare difference in colors. If it only affects Spherical UV, than something could be actually broken.
Also unfortunately not much could be done from this one-sentence report.

**Comment by rakun99** [comment]
> This node is supposed to manipulate UV like any other UV manipulating node and should not change texture colors (I'm not shader guru, but I don't think there are any situations where UV manipulation affects texture colors). Try to use any other UV manipulating node and compare difference in colors. If it only affects Spherical UV, than something could be actually broken. Also unfortunately not much could be done from this one-sentence report.
Yes, I compared this shader to the FishEye shader, which does the same disort in other way, and colors in Fisheye are more bright. Probably because in FishEye you don't load texture from shader parameter. I guess it's inevitable.

https://gist.github.com/aggregate1166877/a889083801d67917c26c12a98e7f57a7

**Comment by arkology** [comment]
Ok I just compared colors or original ShaderV icon and colors of ShaderV icon with applied Spherical UV. No difference, hex numbers are the same. UV shaders does not affect how colors look.

**Comment by arkology** [comment]
May be color space conversion (as I remember `source_color` could could help) or different blend modes.
Closing as not related to plugin. Thanks for report.
