### ISSUE TITLE
"Missing a category" warning in Godot 4.3

### ISSUE THREAD

**Issue by eobet** [arkology/ShaderV#25]
Not sure what this is about?

![image](https://github.com/user-attachments/assets/7113771e-e9b0-4d98-b031-332a519acf97)

**Comment by arkology** [comment]
Oh, it looks like _get_subcategory() was removed in version 4.x and that may be the source of this warning.  But I'm not sure, I've never seen this warning before.

**Comment by arkology** [comment]
Ok, I did stupid test - added custom node from official documentation (https://docs.godotengine.org/en/latest/tutorials/plugins/editor/visual_shader_plugins.html) and have the same warning with officially provided example. And this warning doesn't exist in 4.2.x version.
So there is something wrong with docs or the engine. @eobet could you please open issue in Godot engine repository? I would appreciate it.

**Comment by arkology** [comment]
Will be fixed with next Godot Engine release (4.3.1).
