### ISSUE TITLE
Plugin not detected/installable?

### ISSUE THREAD

**Issue by Knairda0** [arkology/ShaderV#26]
When I place the plugin into my addons folder, it isn't being detected by Godot. I'm using Godot 4.2.2 stable.

![Screenshot 2024-08-08 at 10 27 20 AM](https://github.com/user-attachments/assets/da9a9a4d-ae1e-4578-938e-91ae31ac0b88)

(It seems to be missing plugin.gd and plugin.cfg that PhantomCamera has, not sure if that's it?)

**Comment by arkology** [comment]
See https://docs.godotengine.org/en/stable/classes/class_visualshadernodecustom.html

> The creation process is different from usual editor plugins. You do not need to create a plugin.cfg file to register it; instead, create and save a script file and it will be ready to use, provided the custom node is registered with class_name.

They should not be in the plugin list. They are enabled all the time.
If you want to see them in plugins list, you could open feature proposal in Godot Engine repository.
Have a nice day!
