### ISSUE TITLE
Issues with value of nodes resetting when closing the engine

### ISSUE THREAD

**Issue by Valinakova** [arkology/ShaderV#8]
Hello, when I close the godot engine after saving, I noticed the visual shaders values I set get reset  to the default values. This appears to be a bug. I will be sharing screenshots later but just letting you know this is a bug I found.

**Comment by Valinakova** [comment]
I also get the same issue when duplicating the texture. The values I changed on the new texture go back to their default settings. But not the core sharers that are not part of this addon. How would I fix this?

**Comment by Valinakova** [comment]
Is it possible the way I set up the folders might be causing this issue? 

Here is my folder set up below: 
![image](https://user-images.githubusercontent.com/81381626/114295115-0369d880-9a58-11eb-98f5-45b9d2aa6c6b.png)

**Comment by Valinakova** [comment]
When I duplicated the folder and opened that in the engine, the values reset in this screenshot: 
![image](https://user-images.githubusercontent.com/81381626/114295454-38772a80-9a5a-11eb-905a-a11e51bcbdaa.png)

**Comment by arkology** [comment]
This is engine bug, I can't do anything with it. You should report it in godot repo as bug with VisualShaderNodeCustom set_input_port_default_value().

**Comment by Valinakova** [comment]
Thanks! I will do that.
