### ISSUE TITLE
Plans for the future of this repository

### ISSUE THREAD

**Issue by paddy-exe** [arkology/ShaderV#9]
Hey there,
I've been wanting to create a Shader Node Library myself when stumbling on this repository. First of all: Thank you very much for creating this repository in the first place! Now that Godot 4.0 is on the horizon my question is if there are plans to update the repository to accomodate new functionality such as Vector4s in the Visual Shader Editor. 
This project hasn't been updated recently and I would very much like to contribute some more nodes. However if not desirable, I would otherwise fork this repo and update it in my fork or copy the nodes (and put in the license from here of course) and credit you in the new repository. 

Looking forward to your answer!

**Comment by arkology** [comment]
@paddy-exe hello! I actually have plans to update the plugin this summer (unfortunately I always run out of time, which sucks):
1) refactoring for current Godot 3.x. Master branch will be 3.x-only until 4.0 will be stable.
2) separate brunch for Godot 4.0 (I should check if it's possible to add a link to non-master brunch in Asset library).

I'm not going to abandon this repository, even though there were no updates for a *very* long time.

If you have suggestions for current functionality, feel free to open PR/issues with bugfixes / new functionality, or you can fork and do everything you want, this is how FOSS works :)
